platform :ios,'9.2'
pod 'Masonry','~>0.6.4'
pod 'MJExtension','~>3.0.10'
pod 'AFNetworking','~>3.0.4'


pod 'JPush','~>2.1.0'
pod 'MJRefresh','~>3.1.0'
pod 'FMDB','~>2.6'
pod 'SDWebImage','~>3.7.5'
pod 'Reachability','~>3.2'
pod 'BaiduMapKit'
